### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by LarsStavholm** [infoxchange/pylint-mccabe#1]
Using pylint (0.28.0) with pylint-mccabe (0.1.2) and mccabe (0.2.1) it seems that nothing is actually happening. I've tried setting the max-complexity to very  low, like 2, 3, and so on (and I do have a complexity index reaching 31 for one function, as reported by pymetrics), and still no joy, pylint is not complaining about the complexity.

What gives? How can I troubleshoot this behaviour?

/L

**Comment by koterpillar** [comment]
Can we see your pylint.conf, please?

**Comment by LarsStavholm** [comment]
On Mon, 08 Jul 2013 15:29:48 -0700, Alexey Kotlyarov wrote: 

> Can
> we see your pylint.conf, please?

Yes, of course:

[master]
load-plugins=pylint_mccabe
ignore=guimaker.py

[design]
max-complexity=5

[reports]
symbols=yes
include-ids=yes
output-format=colorized
reports=no

**Comment by koterpillar** [comment]
Apparently, in Python, `10 < '5'`. Fixed, pushed to both Github and PyPI.

**Comment by LarsStavholm** [comment]
And it now works like a charm.
Many thanks!
/L
